# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AI-NeuralNet-Simple
version:      0.01
version_from: Simple.pm
installdirs:  site
requires:
    Inline:                        .44
    Test::Exception:               0.15
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
